name: incomsat-dev

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incomsat-backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: incomsat-frontend-dev
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  frontend_node_modules:
